kernelbakery: remove the "x86-64" from egrep to find the ELF for host…
RevolutionPi/kernelbakery pull request #4
Opened 2020-10-12 10:00 UTC by zhan-kunbus

… machine.

when the kernel is built with debian/update.sh,  some binaries in elf format for
host os are generated.Those files need to be removed from the image for target platform.
this was egrep with "ELF .* x86-64", which gets nothing if the kernel is built on a
non "x86-64" machine

Signed-off-by: Zhi Han <z.han@kunbus.com>

2020-10-12 12:11 UTC, iluminat23 requested changes
So if we don't have any files which are from the wrong architecure, just delete all files? Does this really make sense?

2020-10-12 13:07 UTC, zhan-kunbus commented
this operation is applied to  /usr/src/linux-headers-$version/scripts are just the tools, which is part of the source code, all of the binary under this folder should be re-generatable.

2020-10-13 06:52 UTC, iluminat23 commented
In which step they should be regenerated? At which point?

2020-10-13 09:49 UTC, zhan-kunbus commented
the files being deleted was generated as following: 
shan@KBLinux:~/kernelbakery$ LINUXDIR=$PWD/../linux PIKERNELMODDIR=$PWD/../piControl debian/update.sh
make[1]: Entering directory '/home/shan/kernelbakery/kbuild'
  HOSTCC  scripts/basic/fixdep
  GEN     ./Makefile
  HOSTCC  scripts/kconfig/conf.o
  YACC    scripts/kconfig/zconf.tab.c
  LEX     scripts/kconfig/zconf.lex.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf

And for the afterwards use of those binary, they should be compiled again in the target system, with commands, e.g: make scripts, ...

2020-10-13 10:56 UTC, iluminat23 commented
How do you suggest we run this on the target? Install the linux source and a toolchain and compile these when installing the package?

2020-10-13 12:34 UTC, zhan-kunbus commented
the folders being prepared here are used to build the deb package: raspberrypi-kernel-headers, which is similar to source package: https://packages.debian.org/buster/linux-headers-4.19.0-11-rpi  . As my understanding, it is fine that only source code and scripts are contained in the package. When the binary is needed,  the user can build it by themselves.  we don't need to run it on the target. and regarding to the toolchain dependence, I see that there is also no such dep in the debian package linux-headers-4.19.0-11-rpi, I guess that is not needed.  If it is really needed,  an extra ticket might be needed with different commits to do this.

2020-10-14 08:28 UTC, iluminat23 commented
Close this pull-request for now.

2020-10-14 08:28 UTC, closed without merging

2020-10-14 17:49 UTC, l1k commented
<blockquote>As my understanding, it is fine that only source code and scripts are contained in the package. When the binary is needed, the user can build it by themselves.</blockquote>

No, users have complained about that in the past:
https://revolution.kunbus.de/forum/viewtopic.php?f=6&t=1270&p=5221
https://revolution.kunbus.de/forum/viewtopic.php?f=8&t=1768&p=7758

We run "make kbuild_install" to cross-build fixdep & friends:
https://github.com/RevolutionPi/linux/commit/54d60ba30ae6d3a63020c9005f5c4a0729aba4cd