Don't run xargs on empty string
RevolutionPi/kernelbakery pull request #44
Opened 2022-12-06 17:05 UTC by nbuchwitz

The current approach with fails on systems which are not x86_64 with the following error message:

  LD [M]  sound/usb/line6/snd-usb-line6.ko
  LD [M]  sound/usb/line6/snd-usb-toneport.ko
  LD [M]  sound/usb/misc/snd-ua101.ko
  LD [M]  sound/usb/snd-usb-audio.ko
  LD [M]  sound/usb/snd-usbmidi-lib.ko
make[1]: Leaving directory '/home/pi/kernelbakery/kbuild' rm: missing operand
Try 'rm --help' for more information.

This is caused by the implementation in line 36 of debian/update.sh and the false assumption that there will be always files matching 'ELF .* x86-64'. On other systems where nothing is found 'xargs rm' is called with an empty stdin which fails with the error message above.

Fix this by running xargs only on non-empty input.

This behaviour was initially reported by Simon on 2022-11-22.

Signed-off-by: Nicolai Buchwitz <n.buchwitz@kunbus.com>

2022-12-06 20:59 UTC, nbuchwitz commented
TODO: compare native and cross build kernel headers and check if scripts folder is identical

2022-12-07 07:40 UTC, iluminat23 approved these changes, later dismissed

2022-12-07 08:47 UTC, l1k commented
IIRC, the point here is to remove build tools used by the build host. If you cross-compile on arm64 for arm32, you want to delete the resulting host build tools as well, but the approach proposed here won't achieve that.

I think what you want to do is check if the host build arch is different from the target arch. If so, search for binaries built for the host arch and delete them.

2022-12-22 14:19 UTC, nbuchwitz commented
@l1k I gave it some additional thinking and finally found a generic solution which should work.

@naruxde could you please check if this will work on arm64 host too?

2022-12-23 09:21 UTC, l1k requested changes
Just two nits, otherwise LGTM:

Code comment:
```
    # search for artifacts, which have been built for host architecture and remote them
```
s/remote/remove/ (and the comma is unnecessary ;) )

Commit message:
At least in the kernel community, it is customary to acknowledge the reporter of an issue with a `Reported-by:` tag. Personally, I adhere to the tag ordering used in the PCI subsystem, see <a href="https://marc.info/?l=linux-pci&m=150905742808166#1">here</a> (search for "Order tags as suggested by Ingo").

2022-12-27 21:16 UTC, l1k approved these changes

2022-12-27 21:31 UTC, merged